export const model = [
  { id: 'identifier', name: '№ п/п' },
  { id: 'area', name: 'Районування' },
  { id: 'field', name: '№ поля' },
  { id: 'plant_year', name: 'рік посадки поля' },
  {
    id: 'landlord_by_public_cadastral',
    name: 'Орендодавець згідно Публічної кадастрової карти',
  },
  { id: 'cadastr', name: 'Кадастровий номер' },
  { id: 'size', name: 'Площа земельної ділянки, га', type: 'number' },
  { id: 'contract_date', name: 'Дата договору', type: 'date' },
  { id: 'lease_term', name: 'Строк оренди, років', type: 'number' },
  {
    id: 'lease_term_in_contract',
    name: 'Строк оренди у договорі орендодавця',
    type: 'number',
  },
  { id: 'percent', name: '%', type: 'number' },
  { id: 'owner_dismatch', name: 'Не співпадає власник згідно державного акту' },
  { id: 'note', name: 'Примітки' },
  {
    id: 'sublease_MRIA_FARMING',
    name: 'Договір суборенди ТОВ "МРІЯ ФАРМІНГ ЛЬВІВ"до 06.06.2021 (7 років)',
  },
  {
    id: 'sublease_Colodiy_Mykola',
    name: 'Договір суборенди Колодій Микола Іванович',
  },
  {
    id: 'state_registration_date',
    name: 'Дата державної реєстрації права',
    type: 'date',
  },
  {
    id: 'assessment_date',
    name: 'Дата оцінки ділянки, згідно Держгеокадастру',
    type: 'date',
  },
  { id: 'sum', name: 'Сума, грн', type: 'number' },

  { id: 'state_act_number', name: 'Серія, номер державного акту' },
  { id: 'state_act_date', name: 'Дата видачі державного акту', type: 'date' },
  { id: 'field_type', name: 'Тип землі' },
  { id: 'passport', name: 'Паспорт' },
  { id: 'passport_who', name: 'Виданий ким' },

  { id: 'passport_date', name: 'Виданий, дата', type: 'date' },
  { id: 'identifier_code', name: 'Ідентифікаційний номер' },
  { id: 'phone', name: 'телефон' },
  { id: 'note_2', name: 'примітка' },
  { id: 'additional_relation', name: "Родинний зв'язок" },
  { id: 'additional_name', name: 'ПІБ' },
  { id: 'additional_passport', name: 'паспорт' },
  { id: 'additional_code', name: 'ідентифікаційний код' },
  { id: 'additional_phone', name: 'телефон' },
]
export const sizes = [
  '50px',
  '100px',
  '90px',
  '370px',
  '305px',
  '220px',
  '136px',
  '172px',
  '292px',
  '52px',
  '340px',
  '140px',
  '360px',
  '208px',
  '250px',
  '100px',
  '100px',

  '100px',
  '100px',
  '100px',
  '100px',
  '100px',
  '100px',
  '100px',
  '100px',
  '100px',
  '100px',
  '100px',
  '100px',
  '100px',
  '100px',
]
