import Head from 'next/head'
import Layout from '../components/Layout'
import Dashboard from '../components/dashboard/Dashboard'
import Page from '../components/Page'

export default function Home() {
  return (
    <Page isProtected="true">
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Layout type="dashboard">
        <Dashboard />
      </Layout>
    </Page>
  )
}
