import Head from 'next/head'
import Layout from '../components/Layout'
import Map from '../components/map'

export default function MapPage() {
  return (
    <>
      <Head>
        <title>Map</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout type="map">
        <Map />
      </Layout>
    </>
  )
}
